
--������ 
DROP SEQUENCE USER_SEQ;
DROP SEQUENCE MAGAZINE_SEQ;
DROP SEQUENCE PRODUCT_SEQ;
DROP SEQUENCE MOUNTAIN_SEQ;
DROP SEQUENCE REVIEW_SEQ;

CREATE SEQUENCE USER_SEQ NOCACHE;
CREATE SEQUENCE MAGAZIN_SEQ;
CREATE SEQUENCE PRODUCT_SEQ NOCACHE;
CREATE SEQUENCE MOUNTAIN_SEQ NOCACHE;
CREATE SEQUENCE REVIEW_SEQ NOCACHE;

--���̺�
DROP TABLE LEAVE_USER_T;
DROP TABLE ACCESS_T;
DROP TABLE USER_T;
DROP TABLE REVIEW_T;
DROP TABLE PRODUCT_T;
DROP TABLE MOUNTAIN_T;
DROP TABLE MAGAZIN_MULTI_T;
DROP TABLE MAGAZINE_T;

-- ������ ����� 
CREATE TABLE USER_T (
    USER_NO        NUMBER              NOT NULL,        -- PK
    EMAIL          VARCHAR2(100 BYTE)  NOT NULL UNIQUE, -- �̸����� ���̵�� ���
    PW             VARCHAR2(64 BYTE),                   -- SHA-256 ��ȣȭ ��� ���
    NAME           VARCHAR2(50 BYTE),                   -- �̸�
    GENDER         VARCHAR2(2 BYTE),                    -- M, F, NO
    MOBILE         VARCHAR2(15 BYTE),                   -- ������ ���� �� ����
    POSTCODE       VARCHAR2(5 BYTE),                    -- �����ȣ
    ROAD_ADDRESS   VARCHAR2(100 BYTE),                  -- ���θ��ּ�
    JIBUN_ADDRESS  VARCHAR2(100 BYTE),                  -- �����ּ�
    DETAIL_ADDRESS VARCHAR2(100 BYTE),                  -- ���ּ�
    AGREE          NUMBER              NOT NULL,        -- ���� ���� ����(0:�ʼ�, 1:�̺�Ʈ)
    STATE          NUMBER,                              -- (�ڵ��α���)��������(0:����, 1:���̹�)
    PW_MODIFIED_AT DATE,                                -- ��й�ȣ ������
    JOINED_AT      DATE,                                -- ������
    CONSTRAINT PK_USER PRIMARY KEY(USER_NO)
);

-- ���� ���
CREATE TABLE ACCESS_T (
    EMAIL    VARCHAR2(100 BYTE) NOT NULL,  -- ������ �����
    LOGIN_AT DATE,                         -- �α��� �Ͻ�
    CONSTRAINT FK_USER_ACCESS FOREIGN KEY(EMAIL) REFERENCES USER_T(EMAIL) ON DELETE CASCADE
);

-- Ż���� �����
CREATE TABLE LEAVE_USER_T (
    EMAIL     VARCHAR2(50 BYTE) NOT NULL UNIQUE,  -- Ż���� ����� �̸���
    JOINED_AT DATE,                               -- ������
    LEAVED_AT DATE                                -- Ż����
);


CREATE TABLE MOUNTAIN_T (
	MOUNTAIN_NO	    NUMBER		            NOT NULL,
	PRODUCT_NO	    NUMBER		            NOT NULL,
	MOUNTAIN_NAME	VARCHAR2(150 BYTE)		NOT NULL,
	IMPORMATION	    VARCHAR2(500 BYTE)		NOT NULL,
	LOCATION	    VARCHAR2(100 BYTE)		NOT NULL,
    CONSTRAINT PK_MOUNTAIN_T PRIMARY KEY(MOUNTAIN_NO)
);


CREATE TABLE PRODUCT_T(
	PRODUCT_NO	    NUMBER		            NOT NULL,
	USER_NO	        NUMBER		            NOT NULL,
    MOUNTAIN_NO     NUMBER                  NOT NULL,
	TRIP_NAME	    VARCHAR2(150 BYTE)		NOT NULL,
	TRIP_CONTENTS	CLOB		            NOT NULL,
	GUIDENAME	    VARCHAR2(100 BYTE)		NOT NULL,
	TIMETAKEN	    VARCHAR2(100 BYTE)		NOT NULL,
	PRIZE	        NUMBER		            NOT NULL,
	DANGER	        VARCHAR2(500 BYTE)		NOT NULL,
	REGIST_DATE	    DATE		            NOT NULL,
    MODIFY_DATE     DATE                    NULL,
	PERSON	        NUMBER		            NOT NULL,
	HIT	            NUMBER		            NULL,
	STATUS	        VARCHAR2(100 BYTE)		NULL,
	THUMBNAIL	    NUMBER		            NULL,
	PLAN	        VARCHAR2(255 BYTE)		NULL,
    CONSTRAINT PK_PRODUCT_T PRIMARY KEY(PRODUCT_NO),
    CONSTRAINT FK_USER_NO FOREIGN KEY(USER_NO) REFERENCES USER_TABLE(USER_NO) ON DELETE CASCADE,
    CONSTRAINT FK_MOUNTAIN_NO FOREIGN KEY(MOUNTAIN_NO) REFERENCES MOUNTAIN_T(MOUNTAIN_NO) ON DELETE SET NULL
);


CREATE TABLE REVIEW_T (
	REVIEW_NO	NUMBER		            NOT NULL,
	PRODUCT_NO	NUMBER		            NOT NULL,
	USER_NO	    NUMBER		            NOT NULL,
	CONTENTS	VARCHAR2(300 BYTE)		NULL,
	CREATE_AT	DATE		            NOT NULL,
	MODIFIED_AT	DATE		            NOT NULL,
	STATUS	    VARCHAR2(100 BYTE)		NOT NULL,
	STAR	    INT		NULL,
    CONSTRAINT PK_REVIEW_T PRIMARY KEY(REVIEW_NO),
    CONSTRAINT FK_USER_NO FOREIGN KEY(USER_NO) REFERENCES USER_TABLE(USER_NO) ON DELETE CASCADE,
    CONSTRAINT FK_PRODUCT_NO FOREIGN KEY(PRODUCT_NO) REFERENCES PRODUCT_T(PRODUCT_NO) ON DELETE SET NULL
);


DROP SEQUENCE MAGAZINE_SEQ;

CREATE SEQUENCE MAGAZIN_SEQ;


DROP TABLE MAGAZIN_MULTI_T;
DROP TABLE MAGAZINE_T;


CREATE TABLE MAGAZINE_T (
	MAGAZINE_NO	  NUMBER	 UNIQUE	     NOT NULL,
	USER_NO	      NUMBER		           NOT NULL,
	TITLE	        VARCHAR2(100 BYTE)	 NOT NULL,
	CONTNETS	    CLOB		             NOT NULL,
	STAR	        NUMBER		           DEFAULT 0,
  CREATE_AT	    DATE	        	         NULL,
	HIT	          NUMBER		           DEFAULT 0,
	PRODUCT_NO	  NUMBER		           NOT NULL,
  CONSTRAINT PK_MAGAZINE_NO PRIMARY KEY(MAGAZINE_NO),
  CONSTRAINT FK_USER_MAGAZIN FOREIGN KEY(EMAIL) REFERENCES USER_T(USER_NO) ON DELETE SET NULL,
  CONSTRAINT FK_PRODUCT_MAGAZIN FOREIGN KEY(PRODUCT_NO) REFERENCES PRODUCT_T ON DELETE SET NULL
);



CREATE TABLE MAGAZINE_MULTI_T (
	MAGAZINE_NO	      NUMBER	      	NOT NULL,
	MULTI_PATH	    VARCHAR2(100)		    NULL,
	FILESYS_NAME	  VARCHAR2(100)		    NULL,
  CONSTRAINT FK_MAGAZINE_MULTI FOREIGN KEY(MAGAZINE_NO) REFERENCES MAGAZINE(MAGAZINE_NO) ON DELETE SET NULL  

);
