DROP SEQUENCE NOTICE_SEQ;

CREATE SEQUENCE NOTICE_SEQ NOCACHE;


DROP TABLE NOTICE_T;

-- 공지사항 테이블
CREATE TABLE NOTICE_T (
    NOTICE_NO       NUMBER              NOT NULL,   
    TITLE           VARCHAR2(100 BYTE),
    CONTENTS        CLOB,
    CREATED_AT      DATE,
    HIT             NUMBER,
    CONSTRAINT PK_NOTICE PRIMARY KEY(NOTICE_NO)
); 
    
 INSERT INTO NOTICE_T VALUES (NOTICE_SEQ.NEXTVAL, '내용', '다들 감사합니다', TO_DATE('20231001', 'YYYY-MM-DD'), 2);   
COMMIT;