DROP SEQUENCE NOTICE_SEQ;

CREATE SEQUENCE NOTICE_SEQ NOCACHE;

DROP TABLE NOTICE_T;


CREATE TABLE NOTICE_T (
    NOTICE_NO       NUMBER               NOT NULL, -- 공지 번호
    TITLE           VARCHAR2(100 BYTE),            -- 공지 제목
    CONTENTS        CLOB,                          -- 공지 내용
    CREATED_AT      DATE,                          -- 공지 작성일
    MODIFIED_AT     DATE,                          -- 공지 수정일
    HIT             NUMBER,                        -- 조회수
    CONSTRAINT PK_NOTICE_T PRIMARY KEY(NOTICE_NO)
    ); 


INSERT INTO NOTICE_T VALUES (NOTICE_SEQ.NEXTVAL, '가', '지', TO_DATE('20231018', 'YYYY-MM-DD'), TO_DATE('20231018', 'YYYY-MM-DD'), 1);
INSERT INTO NOTICE_T VALUES (NOTICE_SEQ.NEXTVAL, '가', '지', TO_DATE('20231018', 'YYYY-MM-DD'), TO_DATE('20231018', 'YYYY-MM-DD'), 1);
INSERT INTO NOTICE_T VALUES (NOTICE_SEQ.NEXTVAL, '가', '지', TO_DATE('20231018', 'YYYY-MM-DD'), TO_DATE('20231018', 'YYYY-MM-DD'), 1);
INSERT INTO NOTICE_T VALUES (NOTICE_SEQ.NEXTVAL, '가', '지', TO_DATE('20231018', 'YYYY-MM-DD'), TO_DATE('20231018', 'YYYY-MM-DD'), 1);
INSERT INTO NOTICE_T VALUES (NOTICE_SEQ.NEXTVAL, '가', '지', TO_DATE('20231018', 'YYYY-MM-DD'), TO_DATE('20231018', 'YYYY-MM-DD'), 1);


SELECT A.NOTICE_NO, A.TITLE, A.CONTENTS, A.CREATED_AT, A.MODIFIED_AT, A.HIT
       FROM (SELECT ROW_NUMBER() OVER(ORDER BY NOTICE_NO DESC) AS RN, NOTICE_NO, TITLE, CONTENTS, CREATED_AT, MODIFIED_AT, HIT
               FROM NOTICE_T) A
       WHERE A.RN BETWEEN 1 AND 5;




